---
title: Dota Follower

description: |
  An Ordinary Dota Follower
baseurl: "/"
url: https://erfeng0906.github.io/dotaBlog
paginate: 12
github:
  user: hugocarreira
  repository: jekyll-materializecss
  url: https://erfeng0906.github.io/dotaBlog/
home_bgfile: bg.jpeg
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
exclude:
- vendor
